### ISSUE TITLE
Line by line

### ISSUE THREAD

**Issue by ghost** [stbrumme/toojpeg#8]
Feature idea: allowing the image to be written line by line, so we don't need to allocate a large chunk of memory first.

**Comment by stbrumme** [comment]
That's exactly how libjpeg works.
However, single lines can't be processed because of the 8x8 DCT so that I would have to buffer 8 lines until compression can continue (or 16 lines for 4:2:0 output format). => code complexity would increase a lot. Plus a more complicated library API.

By the way, toojpeg doesn't allocate any memory. Aside from computed images (e.g. raytracing), almost all applications have the full image stored in memory so that I don't see much use of the feature.
